/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import banco.MySQL;
import classes.usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Hendrew
 */
public class pesquisar extends javax.swing.JFrame {
    MySQL conectar = new MySQL(); 
    usuario pesquisarUsuario = new usuario();
    /**
     * Creates new form pesquisar
     */
    public pesquisar() {
        initComponents();
    }
    

private void pesquisarUsuario(usuario pesquisarUsuario){
    this.conectar.conectaBanco(); 
  
    pesquisarUsuario.setCpf(txtConsultaCpf.getText());    
try {  
        this.conectar.conectaBanco();
        
        String txtConsultaCpf = this.txtConsultaCpf.getText();             
           this.conectar.executarSQL(
                   "SELECT "
                    + "nome,"                    
                    + "email,"
                    + "cidade,"
                    + "celular,"
                    + "UF"
                 + " FROM"
                     + " usuario"
                 + " WHERE"
                     + " cpf = '" + txtConsultaCpf + "'"
                + ";");
      
           pesquisarUsuario.limpaCliente();
            while(this.conectar.getResultSet().next()){
                pesquisarUsuario.setNome(this.conectar.getResultSet().getString(1));
                pesquisarUsuario.setEmail(this.conectar.getResultSet().getString(2));
                pesquisarUsuario.setCidade(this.conectar.getResultSet().getString(3));
                pesquisarUsuario.setCelular(this.conectar.getResultSet().getString(4));
                pesquisarUsuario.setUF(this.conectar.getResultSet().getString(5));
           }
           if (pesquisarUsuario.getNome().isEmpty()){
                JOptionPane.showMessageDialog(null, "Usuário não encontrado!");
           }
           
        } catch (Exception e) {            
            System.out.println("Erro ao consultar usuário " +  e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao buscar cliente");
            
        } finally{
            txtPesquisarNome.setText(pesquisarUsuario.getNome());
            txtPesquisarEmail.setText(pesquisarUsuario.getEmail());
            txtPesquisarCidade.setText(pesquisarUsuario.getCidade());
            txtPesquisarCelular.setText(pesquisarUsuario.getCelular());
            txtPesquisarUf.setText(pesquisarUsuario.getUF());
            this.conectar.fechaBanco();   
        }                      
    }
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel41 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        txtPesquisarNome = new javax.swing.JTextField();
        txtPesquisarEmail = new javax.swing.JTextField();
        txtPesquisarCelular = new javax.swing.JFormattedTextField();
        txtPesquisarCidade = new javax.swing.JTextField();
        txtPesquisarUf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtConsultaCpf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar cliente");
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel41.setBackground(new java.awt.Color(0, 0, 0));
        jLabel41.setFont(new java.awt.Font("Nunito SemiBold", 1, 48)); // NOI18N
        jLabel41.setText("Pesquisar Usuário");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(140, 30, 450, 90);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 100, 650, 10);

        jLabel29.setFont(new java.awt.Font("Nunito SemiBold", 1, 19)); // NOI18N
        jLabel29.setText("Digite o CPF");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(230, 120, 130, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Document Writer.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 110, 50, 60);

        btnSair.setFont(new java.awt.Font("Nunito SemiBold", 1, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 25, 37));
        btnSair.setText("Sair");
        btnSair.setActionCommand("");
        btnSair.setBorder(null);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(30, 460, 200, 60);

        btnAtualizar.setFont(new java.awt.Font("Nunito SemiBold", 1, 24)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(0, 25, 37));
        btnAtualizar.setText("Pesquisar");
        btnAtualizar.setBorder(null);
        btnAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar);
        btnAtualizar.setBounds(460, 460, 200, 60);

        txtPesquisarNome.setEditable(false);
        txtPesquisarNome.setFont(new java.awt.Font("Nunito SemiBold", 1, 18)); // NOI18N
        txtPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisarNome);
        txtPesquisarNome.setBounds(20, 230, 350, 30);

        txtPesquisarEmail.setEditable(false);
        txtPesquisarEmail.setFont(new java.awt.Font("Nunito SemiBold", 1, 18)); // NOI18N
        txtPesquisarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisarEmail);
        txtPesquisarEmail.setBounds(20, 290, 330, 30);

        txtPesquisarCelular.setEditable(false);
        try {
            txtPesquisarCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPesquisarCelular.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPesquisarCelular.setFont(new java.awt.Font("Nunito SemiBold", 1, 18)); // NOI18N
        getContentPane().add(txtPesquisarCelular);
        txtPesquisarCelular.setBounds(390, 230, 190, 30);

        txtPesquisarCidade.setEditable(false);
        txtPesquisarCidade.setFont(new java.awt.Font("Nunito SemiBold", 1, 18)); // NOI18N
        txtPesquisarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisarCidade);
        txtPesquisarCidade.setBounds(20, 350, 430, 30);

        txtPesquisarUf.setEditable(false);
        txtPesquisarUf.setFont(new java.awt.Font("Nunito SemiBold", 1, 18)); // NOI18N
        txtPesquisarUf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesquisarUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarUfActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisarUf);
        txtPesquisarUf.setBounds(490, 350, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User Male.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 180, 50, 80);

        jLabel30.setFont(new java.awt.Font("Nunito SemiBold", 1, 19)); // NOI18N
        jLabel30.setText("Nome");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(20, 200, 80, 40);

        jLabel28.setFont(new java.awt.Font("Nunito SemiBold", 1, 19)); // NOI18N
        jLabel28.setText("Celular");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(390, 200, 80, 40);

        jLabel32.setFont(new java.awt.Font("Nunito SemiBold", 1, 19)); // NOI18N
        jLabel32.setText("E-mail");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(20, 260, 80, 40);

        jLabel33.setFont(new java.awt.Font("Nunito SemiBold", 1, 19)); // NOI18N
        jLabel33.setText("Cidade");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(20, 320, 80, 40);

        jLabel31.setFont(new java.awt.Font("Nunito SemiBold", 1, 19)); // NOI18N
        jLabel31.setText("UF");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(490, 320, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mail Account.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 250, 50, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home Page.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 310, 50, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home Page.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 310, 50, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Smartphone.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 190, 60, 60);

        txtConsultaCpf.setFont(new java.awt.Font("Nunito SemiBold", 0, 16)); // NOI18N
        getContentPane().add(txtConsultaCpf);
        txtConsultaCpf.setBounds(200, 160, 210, 29);

        jPanel1.setBackground(new java.awt.Color(166, 190, 196));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
    pesquisarUsuario(pesquisarUsuario);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarNomeActionPerformed

    private void txtPesquisarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarEmailActionPerformed

    private void txtPesquisarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarCidadeActionPerformed

    private void txtPesquisarUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarUfActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesquisar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtConsultaCpf;
    private javax.swing.JFormattedTextField txtPesquisarCelular;
    private javax.swing.JTextField txtPesquisarCidade;
    private javax.swing.JTextField txtPesquisarEmail;
    private javax.swing.JTextField txtPesquisarNome;
    private javax.swing.JTextField txtPesquisarUf;
    // End of variables declaration//GEN-END:variables
}
